package java1;

import Java.

@Entity
@Table (name="employees")
public class Employee {
    @Id
    private int id;
    @Column(name="e_name", nullable=false)
    private String name;
    private long salary;
}

@Entity
@Table (name="students")
class Student{
    @Id
    //id values is generated by database
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private int id;
    @Column(name="matricNumber")
    private String matricNo;
    private String name;

    public Student(){

    }
}
